version: '3.5'

services:
  lighthouse:
    build:
      context: ./app
    restart: always
    ports:
      - 4242:4242/udp
    cap_add: ["NET_ADMIN"]
    privileged: true
    network_mode: host
    volumes:
        - "./config:/nebula"
    command: nebula -config /nebula/config.yml
